import pubg from '@/assets/products/pubg.webp.asset.json'; import freeFire from '@/assets/products/free-fire.webp.asset.json'; import mobileLegends from '@/assets/products/mobile-legends.webp.asset.json'; import roblox from '@/assets/products/roblox.webp.asset.json'; import fortnite from '@/assets/products/fortnite.webp.asset.json'; import cod from '@/assets/products/call-of-duty.webp.asset.json'; import genshin from '@/assets/products/genshin-impact.webp.asset.json'; import valorant from '@/assets/products/valorant.webp.asset.json'; import steam from '@/assets/products/steam.webp.asset.json';
import gpGreen from '@/assets/products/google-play-green.webp.asset.json'; import gpBlue from '@/assets/products/google-play-blue.webp.asset.json'; import gpRed from '@/assets/products/google-play-red.webp.asset.json'; import gpGold from '@/assets/products/google-play-gold.webp.asset.json';
import netflix from '@/assets/products/netflix.webp.asset.json'; import spotify from '@/assets/products/spotify.webp.asset.json'; import youtube from '@/assets/products/youtube-premium.webp.asset.json'; import disney from '@/assets/products/disney-plus.webp.asset.json'; import amazon from '@/assets/products/amazon-prime.webp.asset.json'; import chatgpt from '@/assets/products/chatgpt-plus.webp.asset.json'; import microsoft from '@/assets/products/microsoft-365.webp.asset.json'; import sports from '@/assets/products/sports-streaming.webp.asset.json'; import cloud from '@/assets/products/cloud-storage.webp.asset.json';
export type Product={name:string; subtitle:string; image:string; tag?:string};
const product=(name:string,subtitle:string,image:string):Product=>({name,subtitle,image});
export const games:Product[]=[product('PUBG Mobile','UC top-ups',pubg.url),product('Free Fire','Diamonds',freeFire.url),product('Mobile Legends','Diamonds & passes',mobileLegends.url),product('Roblox','Robux credit',roblox.url),product('Fortnite','V-Bucks',fortnite.url),product('Call of Duty','CP top-ups',cod.url),product('Genshin Impact','Genesis Crystals',genshin.url),product('Valorant','Valorant Points',valorant.url),product('Steam','Wallet credit',steam.url)];
export const playCards:Product[]=[product('Google Play — Green','Digital gift card',gpGreen.url),product('Google Play — Blue','Digital gift card',gpBlue.url),product('Google Play — Red','Digital gift card',gpRed.url),product('Google Play — Gold','Global gift card',gpGold.url)];
export const subscriptions:Product[]=[product('Netflix','Streaming subscription',netflix.url),product('Spotify','Premium music',spotify.url),product('YouTube Premium','Ad-free video',youtube.url),product('Disney+','Movies & series',disney.url),product('Amazon Prime','Prime entertainment',amazon.url),product('ChatGPT Plus','Premium AI access',chatgpt.url),product('Microsoft 365','Productivity suite',microsoft.url),product('Sports Streaming','Live sports access',sports.url),product('Cloud Storage','Secure cloud plans',cloud.url)];
export const wa=(product?:string)=>`https://wa.me/21628415739?text=${encodeURIComponent(product?`Hello, I'd like to order ${product}.`:'Hello, I would like to place an order.')}`;
