import pubg from '@/assets/products/pubg.webp'; import freeFire from '@/assets/products/free-fire.webp'; import mobileLegends from '@/assets/products/mobile-legends.webp'; import roblox from '@/assets/products/roblox.webp'; import fortnite from '@/assets/products/fortnite.webp'; import cod from '@/assets/products/call-of-duty.webp'; import genshin from '@/assets/products/genshin-impact.webp'; import valorant from '@/assets/products/valorant.webp'; import steam from '@/assets/products/steam.webp';
import gpGreen from '@/assets/products/google-play-green.webp'; import gpBlue from '@/assets/products/google-play-blue.webp'; import gpRed from '@/assets/products/google-play-red.webp'; import gpGold from '@/assets/products/google-play-gold.webp';
import netflix from '@/assets/products/netflix.webp'; import spotify from '@/assets/products/spotify.webp'; import youtube from '@/assets/products/youtube-premium.webp'; import disney from '@/assets/products/disney-plus.webp'; import amazon from '@/assets/products/amazon-prime.webp'; import chatgpt from '@/assets/products/chatgpt-plus.webp'; import microsoft from '@/assets/products/microsoft-365.webp'; import sports from '@/assets/products/sports-streaming.webp'; import cloud from '@/assets/products/cloud-storage.webp';
export type Product={name:string; subtitle:string; image:string; tag?:string};
const product=(name:string,subtitle:string,image:string):Product=>({name,subtitle,image});
export const games:Product[]=[product('PUBG Mobile','UC top-ups',pubg),product('Free Fire','Diamonds',freeFire),product('Mobile Legends','Diamonds & passes',mobileLegends),product('Roblox','Robux credit',roblox),product('Fortnite','V-Bucks',fortnite),product('Call of Duty','CP top-ups',cod),product('Genshin Impact','Genesis Crystals',genshin),product('Valorant','Valorant Points',valorant),product('Steam','Wallet credit',steam)];
export const playCards:Product[]=[product('Google Play — Green','Digital gift card',gpGreen),product('Google Play — Blue','Digital gift card',gpBlue),product('Google Play — Red','Digital gift card',gpRed),product('Google Play — Gold','Global gift card',gpGold)];
export const subscriptions:Product[]=[product('Netflix','Streaming subscription',netflix),product('Spotify','Premium music',spotify),product('YouTube Premium','Ad-free video',youtube),product('Disney+','Movies & series',disney),product('Amazon Prime','Prime entertainment',amazon),product('ChatGPT Plus','Premium AI access',chatgpt),product('Microsoft 365','Productivity suite',microsoft),product('Sports Streaming','Live sports access',sports),product('Cloud Storage','Secure cloud plans',cloud)];
export const wa=(product?:string)=>`https://wa.me/21628415739?text=${encodeURIComponent(product?`Hello, I'd like to order ${product}.`:'Hello, I would like to place an order.')}`;
