import { Link } from '@tanstack/react-router';
import { CheckCircle2, Gamepad2, Gift, Menu, MessageCircle, ShieldCheck, Sparkles, X, Zap } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { wa, type Product } from '@/lib/catalog';
export function Logo(){return <Link to="/" className="flex items-center gap-2 font-display text-xl font-bold"><span className="grid size-9 place-items-center rounded-md bg-primary text-primary-foreground shadow-neon"><Zap className="size-5"/></span><span>LEVEL<span className="text-primary">UP</span></span></Link>}
const nav=[['Games','/games'],['Google Play','/google-play'],['Subscriptions','/subscriptions'],['How to order','/how-to-order'],['Support','/support']] as const;
export function Header(){const [open,setOpen]=useState(false);return <header className="fixed inset-x-0 top-0 z-50 border-b border-border/70 bg-background/85 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-4 lg:px-8"><Logo/><nav className="hidden items-center gap-6 lg:flex">{nav.map(([n,to])=><Link key={to} to={to} className="text-sm text-muted-foreground transition hover:text-foreground" activeProps={{className:'text-primary'}}>{n}</Link>)}</nav><div className="flex items-center gap-2"><Button asChild size="lg" className="hidden sm:inline-flex"><a href={wa()} target="_blank" rel="noreferrer"><MessageCircle/>216 284 15739</a></Button><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</Button></div></div>{open&&<nav className="border-t border-border bg-background p-4 lg:hidden">{nav.map(([n,to])=><Link key={to} to={to} onClick={()=>setOpen(false)} className="block rounded-md px-4 py-3 text-muted-foreground hover:bg-accent hover:text-foreground">{n}</Link>)}<Button asChild className="mt-3 w-full"><a href={wa()} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp now</a></Button></nav>}</header>}
export function Footer(){return <footer className="border-t border-border bg-surface"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 md:grid-cols-[1.3fr_1fr_1fr] lg:px-8"><div><Logo/><p className="mt-4 max-w-sm text-sm leading-6 text-muted-foreground">Fast, secure digital top-ups and subscriptions, delivered through friendly WhatsApp support.</p></div><div><p className="mb-3 text-sm font-semibold">Quick links</p>{nav.slice(0,4).map(([n,to])=><Link key={to} to={to} className="mb-2 block text-sm text-muted-foreground hover:text-primary">{n}</Link>)}</div><div><p className="mb-3 text-sm font-semibold">Ready to order?</p><Button asChild size="lg"><a href={wa()} target="_blank" rel="noreferrer"><MessageCircle/>Contact on WhatsApp</a></Button><p className="mt-3 text-xs text-muted-foreground">Available 24/7 · +216 28 415 739</p></div></div><div className="border-t border-border py-5 text-center text-xs text-muted-foreground">© 2026 Top Up Tunisia Pro 🇹🇳 Digital Store. Secure service, instant delivery.</div></footer>}
export function PageShell({children}:{children:ReactNode}){return <><Header/><main className="pt-18">{children}</main><Footer/></>}
export function PageHero({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <section className="border-b border-border bg-hero"><div className="mx-auto max-w-7xl px-4 py-16 lg:px-8 lg:py-24"><p className="mb-4 text-sm font-semibold uppercase tracking-widest text-primary">{eyebrow}</p><h1 className="max-w-4xl font-display text-4xl font-bold leading-tight sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">{copy}</p></div></section>}
export function ProductGrid({products}:{products:Product[]}){return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((p)=><article key={p.name} className="group overflow-hidden rounded-lg border border-border bg-card transition duration-300 hover:-translate-y-1 hover:border-primary/50 hover:shadow-card"><div className="relative aspect-square overflow-hidden"><img src={p.image} alt={`${p.name} digital product`} loading="lazy" width={800} height={800} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-3 top-3 rounded-full border border-success/30 bg-background/85 px-3 py-1 text-xs font-medium text-success backdrop-blur">Instant delivery</span></div><div className="p-5"><p className="text-xs uppercase tracking-widest text-muted-foreground">{p.subtitle}</p><h2 className="mt-1 font-display text-xl font-semibold">{p.name}</h2><Button asChild size="lg" className="mt-5 w-full"><a href={wa(p.name)} target="_blank" rel="noreferrer"><MessageCircle/>Order via WhatsApp</a></Button></div></article>)}</div>}
export function TrustBar(){const items=[{Icon:Zap,text:'Instant delivery'},{Icon:MessageCircle,text:'24/7 support'},{Icon:ShieldCheck,text:'Guaranteed service'},{Icon:CheckCircle2,text:'Easy ordering'}];return <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{items.map(({Icon,text})=><div key={text} className="flex items-center gap-3 border-l-2 border-primary bg-card px-4 py-4 text-sm font-medium"><Icon className="size-5 text-primary"/>{text}</div>)}</div>}
export const categoryIcons={games:Gamepad2,cards:Gift,subs:Sparkles};
