/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GooglePlayRouteImport } from './routes/google-play'
import { Route as HowToOrderRouteImport } from './routes/how-to-order'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SupportRouteImport } from './routes/support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GooglePlayRoute = GooglePlayRouteImport.update({
  id: '/google-play',
  path: '/google-play',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToOrderRoute = HowToOrderRouteImport.update({
  id: '/how-to-order',
  path: '/how-to-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/google-play': typeof GooglePlayRoute
  '/how-to-order': typeof HowToOrderRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/google-play': typeof GooglePlayRoute
  '/how-to-order': typeof HowToOrderRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/google-play': typeof GooglePlayRoute
  '/how-to-order': typeof HowToOrderRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/google-play'
    | '/how-to-order'
    | '/subscriptions'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/google-play'
    | '/how-to-order'
    | '/subscriptions'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/google-play'
    | '/how-to-order'
    | '/subscriptions'
    | '/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRoute
  GooglePlayRoute: typeof GooglePlayRoute
  HowToOrderRoute: typeof HowToOrderRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-play': {
      id: '/google-play'
      path: '/google-play'
      fullPath: '/google-play'
      preLoaderRoute: typeof GooglePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-order': {
      id: '/how-to-order'
      path: '/how-to-order'
      fullPath: '/how-to-order'
      preLoaderRoute: typeof HowToOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRoute,
  GooglePlayRoute: GooglePlayRoute,
  HowToOrderRoute: HowToOrderRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
